#
#
#  â”â”â”â”â”³â”â”â”³â”â”â”â”³â”â”â”â”³â”â”â”â”³â”â”â”â”³â”â”â”â”³â”“â”â”“â”â”³â”“ â”â”³â”â”â”³â”â”â”â”â”³â”â”â”â”³â”“  â”â”â”â”³â”â”â”â”³â”â”â”â”â”“
#  â”—â”“â”â”“â”£â”«â”£â”«â”â”â”“â”ƒâ”â”â”“â”ƒâ”â”â”“â”ƒâ”â”â”“â”£â”“â”â”“â”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”ƒ â”ƒâ”£â”«â”£â”«â”â”“â”â”“â”ƒâ”â”â”â”«â”ƒ  â”—â”«â”£â”«â”â”â”“â”ƒâ”â”“â”â”“â”ƒ
#   â”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”—â”â”â”«â”ƒ â”—â”«â”ƒ â”ƒâ”ƒâ”—â”â”›â”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”—â”â”›â”ƒâ”ƒâ”ƒâ”—â”›â”ƒâ”ƒâ”—â”«â”—â”â”â”«â”ƒ   â”ƒâ”ƒâ”ƒâ”—â”â”â•‹â”›â”ƒâ”ƒâ”—â”›
#   â”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”ƒâ”—â”â”â”“â”ƒâ”ƒ â”â”«â”ƒ â”ƒâ”ƒâ”â”“â”â”›â”ƒâ”ƒâ”ƒâ”ƒâ”—â”›â”—â”›â”ƒâ”â”â”“â”ƒâ”ƒâ”ƒ  â”ƒâ”ƒ â”ƒâ”â”â”â”«â”ƒ â”â”“â”ƒâ”ƒâ”—â”â”â”“â”ƒ â”ƒâ”ƒ
#  â”â”›â”—â”›â”£â”«â”£â”«â”—â”â”›â”ƒâ”—â”â”›â”ƒâ”—â”â”›â”ƒâ”ƒâ”ƒâ”—â”³â”›â”—â”›â”£â”“â”â”“â”â”«â”ƒ â”ƒâ”£â”«â”£â”“ â”ƒâ”ƒ â”ƒâ”—â”â”â”«â”—â”â”›â”£â”«â”£â”«â”—â”â”›â”ƒ â”ƒâ”ƒ
#  â”—â”â”â”â”»â”â”â”»â”â”â”â”»â”â”â”â”»â”â”â”â”»â”›â”—â”â”»â”â”â”â”›â”—â”›â”—â”›â”—â”› â”—â”»â”â”â”› â”—â”› â”—â”â”â”â”»â”â”â”â”»â”â”â”»â”â”â”â”› â”—â”›
#                   ð——ð—œð—¦ð—–ð—¢ð—¥ð——ð—ªð—›ð—œð—§ð—˜ð—Ÿð—œð—¦ð—§ ãƒ» v24.3.4
#                á´á´á´…á´‡Ê€É´ êœ±á´‡Ê€á´ á´‡Ê€ êœ±á´‡á´„á´œÊ€Éªá´›Ê á´€á´œá´›á´á´á´€á´›Éªá´É´
#
# ð–ðˆððƒ ð’ð“ð”ðƒðˆðŽ á“¥ Discord server â˜ https://discord.gg/XMGprbGtgR
# ð——ð—œð—¦ð—–ð—¢ð—¥ð——ð—ªð—›ð—œð—§ð—˜ð—Ÿð—œð—¦ð—§ Wiki page â˜ https://windstudio.gitbook.io/discordwhitelist
#
# ð—§ð—µð—®ð—»ð—¸ð˜€ ð—³ð—¼ð—¿ ð—°ð—µð—¼ð—¼ð˜€ð—² ð——ð—œð—¦ð—–ð—¢ð—¥ð——ð—ªð—›ð—œð—§ð—˜ð—Ÿð—œð—¦ð—§ ð—½ð—¹ð˜‚ð—´ð—¶ð—» â™¥
#

# Section where you NEED to configure basic settings
# without which the plugin will not start
Service:

  # Defines what language will be used to send messages
  # You can translate language file by yourself
  # (and suggest your translation on our Discord server)
  # or use pre-translated supported languages files
  # List of supported languages â˜ https://windstudio.gitbook.io/discordwhitelist/step-by-step-setting/setting-up-our-bot
  Language: en_US

  # Should plugin send message about updates of a plugin
  # to a player(OP & Permission) and in console?
  Check-Updates: true

  # (Requires developer mode enabled)
  # These option let plugin know about server you're on,
  # so plugin will use it for its needs.
  # Copy your server ID using: RMB on your server -> click on COPY ID button
  ServerID: ReplaceThisWithYourServerID

  # You can find Bot Token on Discord Developer Portal â˜ https://discord.com/developers/applications
  # Some instructions how to configure this option:
  #  1 â˜ Go to Discord Developer Portal, create(or choose existing) bot
  #  2 â˜ Go to his settings, then go to 'Bot' page and enable in 'Privileged Gateway Intents' header: PRESENCE INTENT, SERVER MEMBERS INTENT and MESSAGE CONTENT INTENT
  #  3 â˜ Scroll up and tap 'Reset bot token' button, then copy this token and replace 'ReplaceThisWithYourBotToken' with your token
  #  4 â˜ Save config and reload the server
  Token: ReplaceThisWithYourBotToken

  # Since plugin uses unique encryption system for every token,
  # plugin generate a unique password to access your token, so
  # you should enable this if you want to change your token to
  # let plugin generate new password for your new token.
  # Some instructions of usage:
  #  1 â˜ Turn off your server(or, if you use ReloadModule, you can keep server online)
  #  2 â˜ Go to config, then enable TokenReplacement(replace 'false' to 'true')
  #  3 â˜ Replace your current(encrypted) Token with new one
  #  4 â˜ Save your config, then you can enable server(or, if you use ReloadModule, reload plugin)
  # This feature will return to 'false' condition when encryption success
  TokenReplacement: false

  # Current version of plugin's components
  # Please, use this to report any problem related to plugin
  Version:
    Plugin: v24.3.4
    API: v25
    EWhitelist: v1.25.3
    Linking: v1.07
    Modules: v1

  # This thing can help you know what's going on with plugin.
  # There are some indicators of plugin work that'll be changed until plugin setup success:
  #  â˜ LAUNCHED - Plugin was launched for the first time
  #  â˜ TOKEN_ERROR - Plugin can't login bot with token you've provided
  #  â˜ SECURE_ERROR - Plugin can't encrypt/decrypt token you've provided [Contact developer]
  #  â˜ JDA_ERROR - Bot can't login for some reason, possibly errors with JDA [Contact developer]
  #  â˜ INSTALLED - Plugin successfully installed, works fine
  InstallationIndicator: LAUNCHED


# Database-related section, where you can change database type and its settings
Database:

  # Defines which database type plugin will use to store data
  # You can use following types (case-sensitive):
  #  â˜ SQLite - local file database. Designed for small servers
  #  â˜ MySQL - server database. Designed for networks
  Type: SQLite

  # Here you can configure your database
  # We highly recommend you to either configure it before plugin
  # loaded for first time, either to change only login information
  # (for MySQL) and do not touch other things.
  Settings:

    # Section, where you can configure SQLite database
    # We recommend you to do not touch these settings
    SQLite:

      # Name of database file where information will be stored
      DatabaseName: information

      # Name of tables inside the db file
      TableName:

        # Name of table where linking information will store
        Linking: linking_table

        # Name of table where whitelist information will store
        Whitelist: whitelist_table

        # Name of table where login information will store
        LoginPanel: loginpanel_table

    # Section, where you can configure MySQL database
    # We highly recommend you to change only login information
    MySQL:

      # Login information for your MySQL server
      Host:

        # Database dedicated host
        IP: localhost

        # Port of Database dedicated host
        Port: 3306

        # Login of Database dedicated host
        Login: root

        # Password of Database dedicated host
        Password: root

        # Connection timeout(in ms)
        # Change it only when you know what you're doing!
        ConnectionTimeOut: 3000

      # Name of database file where information will be stored
      DatabaseName: information

      # Name of tables inside the db file
      TableName:

        # Name of table where linking information will store
        Linking: linking_table

        # Name of table where whitelist information will store
        Whitelist: whitelist_table

        # Name of table where login information will store
        LoginPanel: loginpanel_table


# Section, where you can configure main features of plugin
Configuration:

  # Section, settings of which related to your bot
  Discord:

    # Discord settings that will affect on Bot
    Bot:

      # Settings of Bot Activity (like what he's playing right now)
      Activity:

        # Defines will plugin change bot's status and activity
        Status&Activities: true

        # Defines which type of status bot will use.
        # Available types(DND = Do Not Disturb):
        # Online | DND | Idle | Invisible
        Status: Online

        # Defines which type of activity bot will use.
        # Available types: Playing | Listening | Watching | Streaming | Competing
        Type: Playing

        # Complements type, like: "Playing Minecraft server | 2 players online"
        # This feature can count online players, so it
        # supports vanish plugins to not count invisible players.
        # Detected and supported vanish plugins you can find
        # at the end of the config.
        # %0 - players online on the server
        Text: "Minecraft Server | %0 players online"

        # Works only with 'Streaming' type!
        # Grants user open this URL while bot "streaming" something.
        # For example, works with 'https://www.twitch.tv/user' & 'https://www.youtube.com/watch?v=ID'
        URL: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

  # Section, settings of which related to Discord-part of plugin
  Plugin:

    # Settings which contains all IDs of channels that plugin will use
    ChannelID:

      # This channel will be defined as channel where
      # users can type their nickname to be whitelisted
      Whitelist: "WhitelistChannelID"

      # That channel will be defined as channel where
      # bot will send welcome messages for whitelisted users
      # Required for WHITELIST_WELCOME_MESSAGE (7) feature
      Global: "GlobalChannelID"

      # This channel will be defined as channel where
      # administrators of Discord-server will receive logs
      # (for example, whitelisting, linking or check)
      # Required for LOGGING (16) feature.
      Logs: "LogsChannelID"

    # Settings which contains all IDs of roles that plugin will use
    RoleID:

      # [Discord Role] Plugin will check for role with this ID(s) when user uses '/whitelist' SlashCommand
      # Grants access to use '/whitelist' SlashCommand
      # Use 'disable' tag to force plugin ignore this role(s)
      # You can use many roles as list as previewed above
      Admin:
        - "123456789123456789"
        - "123456789123456789"

      # RoleID(s) related with whitelisting process
      Whitelist:

        # [Discord Role] Plugin will add role(s) with this ID(s) when user added in whitelist
        # Use 'disable' tag to force plugin ignore this role(s)
        # You can use many roles as list as previewed below
        Add:
          - "123456789123456789"
          - "123456789123456789"
          - "123456789123456789"

        # [Discord Role] Plugin will remove role(s) with this ID(s) when user was whitelisted
        # Use 'disable' tag to force plugin ignore this role(s) as previewed below
        # You can use many roles as list as previewed above
        Remove:
          - "disable"

      # RoleID(s) related with linking process
      Link:

        # [Discord Role] Plugin will add role(s) with this ID(s) when user linked his accounts
        # [] Role(s) will be removed when user unlink his accounts
        # Use 'disable' tag to force plugin ignore this role(s)
        # You can use many roles as list as previewed below
        Add:
          - "123456789123456789"
          - "123456789123456789"
          - "123456789123456789"

        # [Discord Role] Plugin will remove role(s) with this ID(s) when user linked his accounts
        # [] Role(s) will be added back when user unlink his accounts
        # Use 'disable' tag to force plugin ignore this role(s) as previewed below
        # You can use many roles as list as previewed above
        Remove:
          - "disable"

      # RoleID(s) related with reaction process
      Reactions:

        # [Discord Role] Plugin will add role(s) with this ID(s) when player click on ReactionButton
        # Use 'disable' tag to force plugin ignore this role(s) as previewed below
        # You can use many roles as list as previewed above
        Add:
          - "disable"

        # [Discord Role] Plugin will remove role(s) with this ID(s) when player click on ReactionButton
        # Use 'disable' tag to force plugin ignore this role(s) as previewed below
        # You can use many roles as list as previewed above
        Remove:
          - "disable"

      # RoleID(s) related with whitelist/linking process
      Require:

        # [Discord Role] Plugin will require role(s) with this ID(s) to whitelist user
        # Use 'disable' tag to force plugin ignore this role as previewed below
        # You can use many roles as list as previewed above
        Whitelist:
          - "disable"

        # [Discord Role] Plugin will require role(s) with this ID(s) to link accounts
        # Use 'disable' tag to force plugin ignore this role as previewed below
        # You can use many roles as list as previewed above
        Link:
          - "disable"

    # Settings related to blacklist
    Blacklist:

      # Plugin will restrict these nicknames to be whitelisted
      Nickname:
        - "TestNick"
        - "Test_Nick2"

      # Plugin will check user for his Discord Account ID,
      # and if this list contains this ID,
      # he will be restricted to be whitelisted
      ID:
        - "123456789123456789"
        - "123456789123456789"


# Section, where you can turn on/off every feature of plugin,
# configure some of them and read small description of every
# feature, configure EWhitelist and Vanish support
Plugin:

  # Section where you can configure main and most features of plugin
  # Please, read carefully all comments, even if there is too much them
  Settings:

    # Special symbol for 'BEDROCK_SUPPORT' feature
    # User will be able to place this symbol before his nickname
    # in message and plugin will add his nickname
    # with this symbol before nickname in whitelist
    # /!\ It's not actual support of GeyserMC, patience and
    # it will be added in the future.
    BedrockSymbol: "."

    # Type of message that will be used as Welcome Message.
    # This will affect on message style.
    # Available types: EMBED | TEXT
    Message:
      Welcome:
        Type: EMBED

    # !!! â˜ PLEASE, ðƒðŽ ððŽð“ ENABLE 2 SAME FEATURES AT SAME MOMENT - IT WILL FORCE RUN THEM TWICE!
    # Documentation of how-to-use this system:
    #
    # 1 â˜ Section 'Plugin.Settings.Enabled' contains all enabled features that plugin will use as list
    # 2 â˜ To enable some feature, read all description texted below, then scroll down in 'Enabled' section
    #     and add line with that feature in this list feature you need. This will look something like this:
    #     | ...:                     |
    #     | Enabled:                 |
    #     |   - "EPHEMERAL_MESSAGES" |
    #     |   - "EWHITELIST"         |
    #
    # 3 â˜ To disable any feature, you just need remove line with this feature. This will look something like this:
    #     | ...:                     |
    #     | Enabled:                 |
    #     |   - "EPHEMERAL_MESSAGES" |
    #     |                          |
    #     As you can see, feature named "EWHITELIST" does not enabled right now  as shown above
    #
    # By default almost some features commented to disable them, you can enable them by removing '#'
    # before '-', or just remove this line(to be honest, unnecessary) if you don't need them.
    # We hope this mini-tutorial was helpful for you.
    #
    # You can see all this on our wiki with screenshots
    # https://windstudio.gitbook.io/discordwhitelist/step-by-step-setting/plugins-features-and-config#enabled
    # Description of every feature listed below:
    #
    # 1 > EPHEMERAL_MESSAGES: Defines will all messages(except logs) related to plugin be deleted after some time
    # 2 > WHITELIST_ROLE_ADD: Defines will user get role when he was whitelisted. Uses 'RoleID.Whitelist.Add' as role
    # 3 > WHITELIST_ROLE_REMOVE: Defines will user lose role when he was whitelisted. Uses 'RoleID.Whitelist.Remove' as role
    # 4 > BLACKLIST: Defines will blacklist feature be enabled
    # 5 > WHITELIST_CHANGE_NAME: Defines will user's nickname be changed to when he was whitelisted
    # 6 > WHITELIST_DM: Defines will Direct Message be sent to user when he was whitelisted
    # 7 > WHITELIST_WELCOME_MESSAGE: Defines will bot send message into 'ChannelID.Global' channel when user was whitelisted
    # 8 > WHITELIST_CONFIRMATION_MENU: Defines will confirmation menu will send to user when he's trying being whitelisted
    # 9 > EWHITELIST: Defines will plugin use own Nickname-based whitelist system
    # 10 > REACTIONS: Defines will plugin add 'RoleID.Reactions.Add'/remove 'RoleID.Reactions.Remove' when user click on special button
    # 11 > REQUIRE_ROLE: Defines will plugin require role(s) to whitelist 'RoleID.Require.Whitelist'/link user 'RoleID.Require.Link'
    # 12 > REGEX_CHECK: Defines will plugin check nickname before adding/removing it to/from whitelist (for SlashCommand)
    # 13 > BEDROCK_SUPPORT: Defines will plugin allow use 'BedrockSymbol' before nickname and add native support for Geyser(Floodgate)
    # 14 > LINKING: Defines will linking system be turned on and can players(users) use its commands
    # 15 > LINKING_LEFT_USERS_REMOVE: Defines, will plugin unlink user's accounts and remove his from whitelist when he left from Discord server
    # 16 > LINKING_NAME_CHANGE: Defines will linked discord user's nickname changed like his Minecraft nickname (or changed when he unlinked his account)
    # 17 > LOGGING: Defines will plugin send logs(for whitelisting/linking/checking) in channel. Uses 'ChannelID.Logs' as logs channel
    Enabled:
      - "EPHEMERAL_MESSAGES"
      - "WHITELIST_ROLE_ADD"
      #- "WHITELIST_ROLE_REMOVE"
      - "WHITELIST_CHANGE_NAME"
      - "WHITELIST_DM"
      - "WHITELIST_CONFIRMATION_MENU"
      - "EWHITELIST"
      #- "REACTIONS"
      - "BLACKLIST"
      - "REGEX_CHECK"
      #- "BEDROCK_SUPPORT"
      #- "LOGGING"
      #- "LINKING_NAME_CHANGE"
      #- "REQUIRE_ROLE"
      - "LINKING"
      - "LINKING_LEFT_USERS_REMOVE"

    # EWhitelist is nickname-based type of whitelist, which is
    # implemented directly into plugin. You can configure it
    # as you want and as possible.
    EWhitelist:

      # Defines will EWhitelist be enabled (not overrides setting from 'Plugin.Settings.Enabled' section)
      # Can be changed via the command /ewl enable/disable whitelist
      Enabled: false

      # Defines will Maintenance be turned on (only Administrators who was added in EWhitelist will be able to join)
      # Can be changed via the command /ewl enable/disable service
      Maintenance: false

      # Defines, will plugin do a synchronization between EWhitelist and default whitelist (add/remove player)
      # Currently does not synchronize exist players in both systems, only new players
      Sync: true

      # Messages that EWhitelist will use
      Message:

        # EWhitelist kick message when player trying to join the server while he(player) is blacklisted
        Blacklisted: "&cSorry, but you are blacklisted on this server!"

        # EWhitelist kick message when player trying join the server while EWhitelist Maintenance mode turned on
        OnMaintenance: "&cSorry, but this server is on maintenance!"

        # EWhitelist kick message when not whitelisted player trying to join
        NotWhitelisted: "&cSorry, but you need to be whitelisted in order to play on this server!"

  # Section where you can configure Vanish support for plugin
  # This setting is critically important for you if
  # you're using Status&Activities feature, so now,
  # if you configured this, plugin will ignore
  # vanished players when count online players
  Vanish:

    # The list of detected Vanish plugins.
    # You don't have to change it, because it will be
    # updated on every plugin startup
    Detected:
      - None

    # The list of supported Vanish plugins
    # which support will be implemented
    # in plugin, so plugin will use their
    # API to detect vanished players.
    # To enable Vanish plugin support just copy
    # one of plugin's name in 'Detected' section
    # above and paste it here as a list, example:
    # Supported:
    #   - SuperVanish
    Supported:
      - None